project:
  type: book
  output-dir: docs

book:
  title: "RwithSLING"
  author: 
  - name: "Bo Burla"
    affiliation: "Singapore Lipidomics Incubator @ NUS"
  - name: "SLING"
    affiliation: "Singapore Lipidomics Incubator @ NUS"
  date: "5/13/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: tutorials.qmd
      chapters: 
      - import_data.qmd
      - datawrangling.qmd
    - part: recipes.qmd
      chapters: 
      - import_MSdatasets.qmd
    - references.qmd

  page-footer:
    left: |
      R with was written by Singapore Lipidomics Incubator (SLING).
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  site-url: https://slinghub.github.io/RwithSLING/
  repo-url: https://github.com/SLINGhub/RwithSLING/
  repo-branch: master
  repo-actions: [edit, issue]

bibliography: references.bib

format:
  html:
    theme:
      light: 
        - cosmo
        - RwithSLING.scss
      dark: darkly
      code-link: true

  pdf:
    documentclass: scrreprt

editor: visual

